Use TextDecoder to decode uint8Array
eliperelman/taskcluster-tools pull request #1
Opened 2017-06-24 18:15 UTC by helfi92

2017-06-24 23:14 UTC, eliperelman requested changes

2017-06-24 23:14 UTC, eliperelman commented on src/views/Shell/index.js
> +      const DECODER = new TextDecoder('utf-8');
Move this `const` to the top of the file under the imports.

2017-06-26 14:06 UTC, eliperelman commented
@helfi92 can you rebase? I've made a few rearrangements to splitting up the component and the view into separate files where appropriate.

2017-06-27 01:21 UTC, helfi92 commented
Having some trouble rebasing. Created #3 instead.

2017-06-27 01:21 UTC, closed without merging